services:
  nginx:
    image: nginx:latest
    container_name: yogi_poke_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - server
      - storage
      - ci-server