version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./html:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot -w /var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d yogi-poke-api.is-not-a.store -d ci-server.is-not-a.store -d static.is-not-a.store -d yogi-poke-database.is-not-a.store -d static.console.is-not-a.store; sleep 12h; done;'"
