name: Lighthouse CI

on: workflow_dispatch

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install LHCI CLI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI for Search Page
        run: lhci collect --url=${{ secrets.VERCEL_URL }}/search --output-dir=./.lighthouseci/search

      - name: Run Lighthouse CI for User Page
        run: lhci collect --url=${{ secrets.VERCEL_URL }}/user/dlx --output-dir=./.lighthouseci/user

      - name: Run Lighthouse CI for My Page
        run: lhci collect --url=${{ secrets.VERCEL_URL }}/my-page --output-dir=./.lighthouseci/my-page

      - name: Install MinIO client
        run: wget https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x mc

      - name: Configure MinIO client
        run: |
          ./mc alias set storage https://static.is-not-a.store ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}

      - name: Upload Lighthouse reports to MinIO
        run: |
          ./mc cp -r ./.lighthouseci/search/ storage/lighthouse/search/
          ./mc cp -r ./.lighthouseci/user/ storage/lighthouse/user/
          ./mc cp -r ./.lighthouseci/my-page/ storage/lighthouse/my-page/

      - name: Create comment with Lighthouse report links
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context } = require('@actions/github');
            const prNumber = context.payload.pull_request ? context.payload.pull_request.number : null;
            if (prNumber) {
              github.rest.issues.createComment({
                ...context.repo,
                issue_number: prNumber,
                body: `Lighthouse reports (mobile) are available:\n
                - [Search page](https://static.is-not-a.store/lighthouse/search/)\n
                - [User page](https://static.is-not-a.store/lighthouse/user/)\n
                - [My Page](https://static.is-not-a.store/lighthouse/my-page/)`
              });
            }
