name: Update Server Container

on:
  push:
    branches:
      - master
    paths:
      - "server/**"

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/yogi-poke:latest

      - name: Send request to upgrade container
        run: |
          curl -X POST https://ci-server.is-not-a.store/upgrade-container \
               -H "Authorization: ${{ secrets.CI_SERVER_TOKEN }}" \
               -H "Content-Type: application/json" \              
               --max-time 300 \
               -d '{
                     "image_name": "donghyunlee022/yogi-poke:latest",
                     "container_name": "yogi_poke_server",
                     "ports": {
                       "8080": 8080
                     }
                   }'
