name: Update Server Container

on:
  push:
    branches:
      - master
    paths:
      - "server/**"

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create .env file
        run: |
          touch ./server/.env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> ./server/.env
          echo STORAGE_ENDPOINT=${{ secrets.STORAGE_ENDPOINT }} >> ./server/.env
          echo STORAGE_PORT=${{ secrets.STORAGE_PORT }} >> ./server/.env
          echo STORAGE_ASSET_BUCKET_ID=${{ secrets.STORAGE_ASSET_BUCKET_ID }} >> ./server/.env
          echo STORAGE_ACCESS_KEY=${{ secrets.STORAGE_ACCESS_KEY }} >> ./server/.env
          echo STORAGE_SECRET_KEY=${{ secrets.STORAGE_SECRET_KEY }} >> ./server/.env
          echo USER_SECRET=${{ secrets.USER_SECRET }} >> ./server/.env
          echo PORT=${{ secrets.PORT }} >> ./server/.env
          echo SERVER_URL=${{ secrets.SERVER_URL }} >> ./server/.env
          echo VAPID_SUBJECT=${{ secrets.VAPID_SUBJECT }} >> ./server/.env
          echo VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }} >> ./server/.env
          echo VAPID_PRIVATE_KEY=${{ secrets.VAPID_PRIVATE_KEY }} >> ./server/.env
          echo CLIENT_HOST=${{ secrets.CLIENT_HOST }} >> ./server/.env
          echo CLIENT_URL=${{ secrets.CLIENT_URL }} >> ./server/.env

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/yogi-poke:latest

      - name: Send request to upgrade container
        run: |
          curl https://ci-server.is-not-a.store/deploy-server-container -H "Authorization: ${{ secrets.CI_SERVER_TOKEN }}"
