name: Update Server Container

on:
  push:
    branches:
      - master
    paths:
      - "server/**"

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send request to remove container
        run: |
          curl -X POST http://ci-server.is-not-a.store/remove-container \
               -H "Authorization: ${{ secrets.CI_SERVER_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{"container_id": "yogi_poke_server"}'

      - name: Send request to start container
        run: |
          curl -X POST http://ci-server.is-not-a.store/start-container \
               -H "Authorization: ${{ secrets.CI_SERVER_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{
                     "image_name": "donghyunlee022/yogi-poke:latest",
                     "container_name": "yogi_poke_server",
                     "ports": {
                       "8080": 8080
                     }
                   }'
